name: Sync Upstream

env:
  FRONTEND_REPO: "https://github.com/totrieuvy/SWP.git"
  BACKEND_REPO: "https://github.com/LearningCoding101/SWP_Jewelry.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  BRANCH: "main"
  BRANCHFE: "master"

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Clone Frontend Repository
        run: |
          git clone --branch ${{ env.BRANCHFE }} ${{ env.FRONTEND_REPO }} CODING/FE

      - name: Clone Backend Repository
        run: |
          git clone --branch ${{ env.BRANCH }} ${{ env.BACKEND_REPO }} CODING/BE

      - name: Copy Frontend to Repo
        run: |
          cp -r CODING/FE/* .

      - name: Copy Backend to Repo
        run: |
          cp -r CODING/BE/* .

      - name: Commit and Push changes
        run: |
          git config --global user.name "LearningCoding101"
          git config --global user.email "hahoang33322@gmail.com"
          git add .
          git commit -m "Sync repositories"
          git push origin ${{ env.BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
